language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
- grunt test

deploy:
  provider: heroku
  all_branches: true
  api_key:
    secure: lF6Cr1rlCBemdOgid8BK2JSWHONsMAy0VuvMvESGn7Y0d4g0EiZH3ZZBYDqKzmnszs4Ce6KLwq1Y313aRJutondypwOljKh0uYFVK3CQ2CIg6KxbD3OObr66Ydtpyddi7pgYQoGY8bxzfPHKRTlLvubEESxA0ucTjjFoMKeEs5Q=
  app: ng-animi
  on:
    repo: Wildhoney/ngAnimi
